### ISSUE TITLE
Only in Python!=3.8.5 TypeError: the JSON object must be str, bytes or bytearray, not dict

### ISSUE THREAD

**Issue by jimdevops19** [red-hat-storage/rlockerservices#9]
When a new queue enters, there is an issue parsing the JSON object when the queue service tries to put queues on pending.

```
Traceback (most recent call last):
  File "C:\RedHat\rlockerservices-1\run.py", line 40, in <module>
    func()
  File "C:\RedHat\rlockerservices-1\run.py", line 9, in actions_queue_
ervice
    svc.run()
  File "C:\RedHat\rlockerservices-1\queue_service\queue_service.py", l
ne 28, in run
    self.put_queues_on_pending()
  File "C:\RedHat\rlockerservices-1\queue_service\queue_service.py", l
ne 83, in put_queues_on_pending
    queue_response = rlocker.change_queue(queue_id, status="PENDING")
  File "C:\Users\jsc\AppData\Local\Programs\Python\Python310\lib\site-
ackages\rlockertools\resourcelocker.py", line 173, in change_queue
    data_section = json.loads(req.json().get('data'))
  File "C:\Users\jsc\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray,

TypeError: the JSON object must be str, bytes or bytearray, not dict

C:\RedHat\rlockerservices-1>
```

**Comment by jimdevops19** [comment]
Issue solved in rlockertools repo. Still needs testing after unfreezing the rlockertools version
